[smb] Move firewall_checker to built-in function & bugs fix
mpgn/CrackMapExec pull request #114
Opened 2023-08-19 13:43 UTC by XiaoliChan

Changes:
- Move `firewall_checker` into the built-in function as `dcom_FirewallChecker` (Preparation for rewriting RDP modules: #66 )
- SMB/AT/MMC command execution exceptions review.
- Firewall check in MMCExec.

2023-08-19 13:53 UTC, XiaoliChan commented
I think moving the `firewall_checker` into the built-in function is the best way for somebody who wants to write smb module with wmi.

2023-08-22 08:54 UTC, XiaoliChan commented
@bongobongoland can you give a test about the new RDP module?

2023-08-22 08:57 UTC, XiaoliChan commented
Target system: server 2019
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/f230c228-567c-44ca-9790-eeaaacf516c3)

For old system: server 2003
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/fd6a3e5e-ff96-46a5-92de-3a7b04e67b25)

2023-08-22 11:55 UTC, bongobongoland commented
I'm on it

2023-08-22 12:29 UTC, XiaoliChan commented
> What does OLD=true mean?

For the old system like server 2003 (under NT6)

2023-08-22 12:35 UTC, bongobongoland commented
<img width="1512" alt="2023-08-22_22-34" src="https://github.com/mpgn/CrackMapExec/assets/129246896/66d17da5-cfa4-41ce-a61c-d4ebc0efeb06">

2023-08-22 12:36 UTC, XiaoliChan commented
> <img alt="2023-08-22_22-34" width="1512" src="https://user-images.githubusercontent.com/129246896/262351425-66d17da5-cfa4-41ce-a61c-d4ebc0efeb06.png">

Nice catch!

2023-08-22 12:37 UTC, XiaoliChan commented
Can you test with disabled firewall?

2023-08-22 12:46 UTC, bongobongoland commented
Works fine now. BUT I had to "netsh advfirewall set allprofiles state off"
I think the module should either disable the firewall (not pretty) or "netsh firewall set service type = remotedesktop mode = enable" (prettier) or something like that, as I suggested earlier.

2023-08-22 12:49 UTC, XiaoliChan commented
> Works fine now. BUT I had to "netsh advfirewall set allprofiles state off" I think the module should either disable the firewall (not pretty) or "netsh firewall set service type = remotedesktop mode = enable" (prettier) or something like that, as I suggested earlier.

Hmm, I still try to figure out how to enable RDP in smb without touching CMD

2023-08-22 12:58 UTC, bongobongoland commented
So...  running "netsh firewall set service type = remotedesktop mode = enable" is not enough. obviously. 
It seems that the firewall has to be disabled completely, only then wmi works fine.

2023-08-22 13:16 UTC, XiaoliChan commented
> So... running "netsh firewall set service type = remotedesktop mode = enable" is not enough. obviously. It seems that the firewall has to be disabled completely, only then wmi works fine.

I have read a post about using the registry to control firewall rules, but it didn't work......

2023-08-22 13:19 UTC, XiaoliChan commented
@bongobongoland BTW, can you test again with this PR with firewall enabled.

2023-08-22 22:36 UTC, bongobongoland commented
I'm on it.

2023-08-23 01:14 UTC, XiaoliChan commented
> I'm on it.

any feedback？

2023-08-23 02:43 UTC, bongobongoland commented
First find. Well. Not really :) Some older machines need the following:

```
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v IgnoreRegUserConfigErrors /t REG_DWORD /d 1 /f
```

But I guess that is not relevant to your code :)

2023-08-23 02:45 UTC, bongobongoland commented
ACTION=status would be good.
Spits out, say, the following: TermService is already running on port 3395

2023-08-23 02:45 UTC, bongobongoland commented
I'm still testing it.

> > I'm on it.
> 
> any feedback？

2023-08-23 02:49 UTC, XiaoliChan commented
> 

Ignore certificates? you can do this in your xfreerdp with `/cert-ignore /tls-seclevel:0 /timeout:80000`

2023-08-23 02:55 UTC, XiaoliChan commented
> ACTION=status would be good. Spits out, say, the following: TermService is already running on port 3395

Hmmm, not going to do this, this needs to do another query stuff...

2023-08-23 03:13 UTC, XiaoliChan commented
> First find. Well. Not really :) Some older machines need the following:
> 
> ```
> reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v IgnoreRegUserConfigErrors /t REG_DWORD /d 1 /f
> ```
> 
> But I guess that is not relevant to your code :)

Any reference to this registry?

2023-08-23 03:59 UTC, bongobongoland commented
> > 
> 
> Ignore certificates? you can do this in your xfreerdp with `/cert-ignore /tls-seclevel:0 /timeout:80000`

no, IgnoreRegUserConfigErrors is about https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-access-denied

2023-08-23 04:25 UTC, XiaoliChan commented
> no, IgnoreRegUserConfigErrors is about https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-access-denied

Well, I didn't see that case, can you pint a screenshot of this error?

2023-08-23 04:33 UTC, bongobongoland commented
I agree.
So for I'm not seeing any errors with the module.

2023-08-23 04:39 UTC, XiaoliChan commented
@NeffIsBack @mpgn Can do review now!

2023-08-23 09:30 UTC, mpgn commented on cme/protocols/smb.py
>      def wmi(self, wmi_query=None, namespace=None):
i think we can remove this function if we go with a new proto wmi

2023-08-23 09:33 UTC, XiaoliChan commented on cme/protocols/smb.py
>      def wmi(self, wmi_query=None, namespace=None):
> i think we can remove this function if we go with a new proto wmi

Sure!

2023-08-23 09:34 UTC, XiaoliChan commented on cme/protocols/smb.py
>      def wmi(self, wmi_query=None, namespace=None):
Do you mean remove the whole `wmi` query function in smb?

2023-08-23 09:36 UTC, XiaoliChan commented on cme/protocols/smb.py
>      def wmi(self, wmi_query=None, namespace=None):
I will make a new PR, if the `WMI` protocol is merged, to many things in this PR.

2023-08-23 12:33 UTC, mpgn requested changes
stacktrace with option --wmi

2023-08-23 12:37 UTC, XiaoliChan commented on cme/modules/rdp.py
> +                "System\\CurrentControlSet\\Control\\Lsa",
Yes, this is for restricted admin

2023-08-23 12:55 UTC, mpgn commented
I feel like this dns related (aka because no dns) but it should not popup a stacktrace like this

2023-08-23 12:57 UTC, XiaoliChan commented
> Not better

Weird, Looks like making the Dcom connection failed on your target.

What happen if you try to execute command via wmiexec?

2023-08-23 12:59 UTC, XiaoliChan commented
Ohhhh, I know where is the issues XD

2023-08-23 13:00 UTC, mpgn commented
But what i'm looking for is a clean error instead of full stracktrace

2023-08-23 13:01 UTC, mpgn requested changes

2023-08-23 13:01 UTC, mpgn commented on cme/protocols/smb.py
> +from impacket.dcerpc.v5.dtypes import NULL
place them with all the impacket line just before :)

2023-08-23 13:02 UTC, XiaoliChan commented
Please test again, I forgot change the `self.conn.getRemoteHost() to self.host`

2023-08-23 13:06 UTC, XiaoliChan commented
> Will it be compatible with Kerberos ? Maybe `self.host if not self.kerberos else self.hostname + "." + self.domain` is better

Awesome !

2023-08-23 13:09 UTC, XiaoliChan commented
> Will it be compatible with Kerberos ? Maybe `self.host if not self.kerberos else self.hostname + "." + self.domain` is better

Done!

2023-08-23 13:16 UTC, mpgn commented
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/b4816c81-6cb2-4840-a79e-6614880240c0)

🎉

2023-08-23 13:19 UTC, mpgn commented
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/d9ad1b17-f8a1-4647-a918-062253eee5fc)


🎉

2023-08-23 13:20 UTC, XiaoliChan commented
> ![image](https://user-images.githubusercontent.com/5891788/262681254-d9ad1b17-f8a1-4647-a918-062253eee5fc.png)
> 
> 🎉

Can you try "-o METHOD=smb ACTION=enable", make sure I not break the `ncacn_np` way

2023-08-23 13:20 UTC, mpgn submitted a review, later dismissed

2023-08-23 13:21 UTC, mpgn commented
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/59d70e38-a05d-4adf-9357-72bc6811b4ec)

🎉

2023-08-23 13:32 UTC, XiaoliChan commented
> ![image](https://user-images.githubusercontent.com/5891788/262681943-59d70e38-a05d-4adf-9357-72bc6811b4ec.png)
> 
> 🎉

Awesome!

2023-08-25 12:43 UTC, XiaoliChan commented
@NeffIsBack Hello Neff, please do a review about this PR (think there were too many messages in your box that made you forget this 😁)

2023-08-25 13:10 UTC, XiaoliChan commented
> @XiaoliChan i already left comments :D
> 
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/61382599/263275308-661181d1-bafd-4717-93d1-905920fdfddd.png">

Hmm, weird, I can't see that

2023-08-25 13:11 UTC, NeffIsBack commented
> Hmm, weird, I can't see that

Ah that might be my fault, sec

2023-08-25 13:12 UTC, XiaoliChan commented
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/61382599/263275308-661181d1-bafd-4717-93d1-905920fdfddd.png">

The SMB, means (ncacn_np), the WMI means (ncacn_tcp_ip), also can mean "executing using smb"

2023-08-25 13:13 UTC, XiaoliChan commented
> Ah that might be my fault, sec

Not sure what happen
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/60e225d8-e8ae-46e1-aadd-6cdb2b67752e)

2023-08-25 13:14 UTC, NeffIsBack requested changes
Rest looks good to me

2023-08-25 13:14 UTC, NeffIsBack commented on cme/modules/rdp.py
> +        METHOD       wmi(ncacn_ip_tcp)/smb(ncacn_np) (choices: wmi, smb, default is wmi)
The Option comments for "OLD" and "DCOM-TIMEOUT" are missing

2023-08-25 13:14 UTC, NeffIsBack commented on cme/modules/rdp.py
> +            context.log.info("Doing action with WMI(ncacn_ip_tcp)")
Same for this, i think that should be more concret

2023-08-25 13:16 UTC, XiaoliChan commented on cme/modules/rdp.py
> +            context.log.info("Doing action with SMB(ncacn_np)")
Yes, should I change it to "Executing over SMB"?

2023-08-25 13:17 UTC, NeffIsBack commented
> The SMB, means (ncacn_np), the WMI means (ncacn_tcp_ip), also can mean "executing using smb"

Ah okay, maybe something like "Using SMB with ncacn_np" or "Executing commands using WMI (ncacn_tcp_ip)"?

2023-08-25 13:19 UTC, XiaoliChan commented
> Ah okay, maybe something like "Using SMB with ncacn_np" or "Executing commands using WMI (ncacn_tcp_ip)"?

Yes

2023-08-25 13:23 UTC, XiaoliChan commented on cme/modules/rdp.py
> +            context.log.info("Doing action with WMI(ncacn_ip_tcp)")
Done!

2023-08-25 13:23 UTC, XiaoliChan commented on cme/modules/rdp.py
> +            context.log.info("Doing action with SMB(ncacn_np)")
Fixed!

2023-08-25 13:26 UTC, NeffIsBack commented
Ah would be nice if you would add the default value for dcom-timeout

2023-08-25 13:28 UTC, XiaoliChan commented
> Ah would be nice if you would add the default value for dcom-timeout (To the module option comment)

Already add in line 59 https://github.com/mpgn/CrackMapExec/pull/114/files#diff-b5c2077d8eda2116d690da1dba11b2bd82d473b5d6bcf88d421535e8bb0217f7R59

2023-08-25 13:30 UTC, NeffIsBack commented
> > Ah would be nice if you would add the default value for dcom-timeout (To the module option comment)
> 
> Already add in line 59 https://github.com/mpgn/CrackMapExec/pull/114/files#diff-b5c2077d8eda2116d690da1dba11b2bd82d473b5d6bcf88d421535e8bb0217f7R59

sorry, i mean't the module option comment. Saw your default value in the code and i think it would be good for the user to know that it already has a default value (so the user does not need to specify it)

2023-08-25 13:30 UTC, XiaoliChan commented
> sorry, i mean't the module option comment. Saw your default value in the code and i think it would be good for the user to know that it already has a default value (so the user does not need to specify it)

Ha, I get it!

2023-08-25 13:31 UTC, NeffIsBack approved these changes
LGTM 👍

2023-08-25 13:32 UTC, XiaoliChan commented
@NeffIsBack Fixed!

2023-08-25 17:42 UTC, mpgn approved these changes

2023-08-25 17:42 UTC, merged

2023-08-26 12:00 UTC, bongobongoland commented
<img width="1192" alt="2023-08-26_21-59" src="https://github.com/mpgn/CrackMapExec/assets/129246896/c5f57f7d-d8b1-40bd-8607-7fefa6d80c52">

When running -M rdp -o ACTION=enable

2023-08-26 12:02 UTC, XiaoliChan commented
> <img alt="2023-08-26_21-59" width="1192" src="https://user-images.githubusercontent.com/129246896/263463059-c5f57f7d-d8b1-40bd-8607-7fefa6d80c52.png">
> When running -M rdp -o ACTION=enable

Looks like something is wrong with DCOM, can you run wmiexec.py with --debug

2023-08-26 12:07 UTC, bongobongoland commented
like this?
<img width="740" alt="2023-08-26_22-06" src="https://github.com/mpgn/CrackMapExec/assets/129246896/2b690a08-9e5c-403f-b207-d3872c9c8294">

2023-08-26 12:08 UTC, XiaoliChan commented
> like this? <img alt="2023-08-26_22-06" width="740" src="https://user-images.githubusercontent.com/129246896/263463405-2b690a08-9e5c-403f-b207-d3872c9c8294.png">

No just impacket's wmiexec.py
Please open a new issues ticket.

2023-08-26 12:18 UTC, bongobongoland commented
Impacket's wmiexec works fine.

2023-08-26 12:20 UTC, XiaoliChan commented
> Impacket's wmiexec works fine.

Please open a new issues ticket and show me the details.