LDAP Enumeration and Add Computer Modules
mpgn/CrackMapExec pull request #37
Opened 2023-07-10 20:34 UTC by Cyb3rC3lt

Migrating to a new PR:As requested, moving my PR to the new Repo. Modules within are:

GROUP-MEM - Used to enumerate Groups within AD and return all their users or computers
COMP-DESC - Used to enumerate Computer accounts by any description text provided
ADD-COMPUTER - A port of Impackets addcomputer.py to CME

Further details and screenshots can be found here:
https://github.com/Cyb3rC3lt/CrackMapExec-Modules

2023-07-10 21:43 UTC, NeffIsBack commented
Nice that looks good, thanks👍🏼

2023-07-11 20:12 UTC, mpgn requested changes

2023-07-11 20:12 UTC, mpgn commented on cme/modules/add_computer.py
> +    name = 'ADD-COMPUTER'
in lower case :)

2023-07-11 20:12 UTC, mpgn commented on cme/modules/comp_desc.py
> +    name = 'COMP-DESC'
in lower case :)

2023-07-11 20:12 UTC, mpgn commented on cme/modules/group_members.py
> +    name = 'GROUP-MEM'
in lower case :)

2023-07-11 20:13 UTC, mpgn commented
Everything is working on my lab, just put the name of the modules in lowercase to keep the formating like other modules :)

2023-07-11 20:24 UTC, Cyb3rC3lt commented
> Everything is working on my lab, just put the name of the modules in lowercase to keep the formating like other modules :)

That's great to hear 😊. Just made those lowercase changes.

2023-07-11 20:40 UTC, mpgn approved these changes

2023-07-11 20:41 UTC, mpgn commented on cme/modules/comp_desc.py
> +                 IP = socket.gethostbyname(answer[0])
the indentation is rather strange

2023-07-11 20:43 UTC, mpgn commented on cme/modules/comp_desc.py
> +sys.setrecursionlimit(10000)
what's that ?

2023-07-11 20:44 UTC, Cyb3rC3lt commented on cme/modules/comp_desc.py
> +                 IP = socket.gethostbyname(answer[0])
I'll take a look at this now, maybe something strange happened when moving it across.

2023-07-11 20:51 UTC, Cyb3rC3lt commented on cme/modules/comp_desc.py
> +sys.setrecursionlimit(10000)
I think I remember putting this in as safeguard to prevent the query returning data. Got it from here: https://www.geeksforgeeks.org/python-sys-setrecursionlimit-method/

2023-07-11 20:54 UTC, mpgn commented on cme/modules/comp_desc.py
> +sys.setrecursionlimit(10000)
it's better if remove :)

2023-07-11 20:59 UTC, Cyb3rC3lt commented on cme/modules/comp_desc.py
> +sys.setrecursionlimit(10000)
Sorted, removed now and improved the indentation :-)

2023-07-12 07:33 UTC, mpgn approved these changes

2023-07-12 07:48 UTC, mpgn commented
Merged, contact me on twitter to get your coin 🎉

2023-07-12 07:48 UTC, merged