Added option to wdigest module to check registry key without editing it
mpgn/CrackMapExec pull request #4
Opened 2023-06-27 13:44 UTC by probird5

Added this option for since I need it on a pentest where the client wanted a lit of hosts with wdigest enabled. Did not want to modify or add existing key.

![vmware_EQ1tgrJNa9](https://github.com/mpgn/CrackMapExec/assets/52969604/2bdfcc2a-de48-4d50-be71-2cd59e5d338c)

2023-06-27 17:10 UTC, NeffIsBack commented
There were some formatting changes with single and double quotation marks that would be reverted by your PR. Can you check that?😊

2023-06-27 17:39 UTC, probird5 commented
> There were some formatting changes with single and double quotation marks that would be reverted by your PR. Can you check that?😊

Sorry about that, should be fixed now.

2023-06-28 21:26 UTC, mpgn requested changes

2023-06-28 21:26 UTC, mpgn commented on cme/modules/wdigest.py
> +                    context.log.error("UseLogonCredential registry key is disabled (registry key not found)")
can you update to context.log.fail(...) :)

2023-06-28 21:26 UTC, mpgn commented on cme/modules/wdigest.py
> +                    context.log.error("UseLogonCredential registry key not present")
can you update to context.log.fail(...) :)

2023-06-28 21:26 UTC, mpgn commented
Can you also add the "check" on the option list:

https://github.com/mpgn/CrackMapExec/pull/4/files#diff-d259610f4607f5b77a14ce1b3cc61f0820e107c1fc564a8cf2b73afe446bf274R19

2023-06-28 23:07 UTC, probird5 commented on cme/modules/wdigest.py
> +                    context.log.error("UseLogonCredential registry key is disabled (registry key not found)")
Done :)

2023-06-28 23:07 UTC, probird5 commented on cme/modules/wdigest.py
> +                    context.log.error("UseLogonCredential registry key not present")
Done :)

2023-06-29 08:10 UTC, mpgn approved these changes

2023-06-29 08:10 UTC, merged