[New protocol] WMI
mpgn/CrackMapExec pull request #68
Opened 2023-08-03 06:57 UTC by XiaoliChan

WMI Brute force, for more details: [#657](https://github.com/Porchetta-Industries/CrackMapExec/pull/657)

Everythings work now

- With smb
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/f4235a07-e50a-45b0-92ca-2aaccf01779e)

- With the domain specified
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/02c5379c-3fbe-4a31-a5bd-02b42bf6409a)

- With `--no-smb`
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/ad22417d-1f37-4dd8-8a55-134c07d2752a)

2023-08-07 08:22 UTC, XiaoliChan commented
@mpgn I can confirm everything works now, please give a review :)

2023-08-07 08:27 UTC, mpgn commented
okay ^^

2023-08-07 14:52 UTC, mpgn requested changes

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Waiting {}s for command completely executed.".format(self.interval_time))
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Save file to: " + resultTXT)
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Adding base64 strings to registry, path: %s, keyname: %s"%(registry_Path,keyName))
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Waiting {}s for command completely executed.".format(self.interval_time))
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Remove temporary files")
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Get result:")
self.logger.info

2023-08-07 14:52 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Remove temporary registry Key")
self.logger.info

2023-08-07 14:53 UTC, mpgn commented
I request changes so it only print the command result

2023-08-07 14:55 UTC, XiaoliChan commented
> I request changes so it only print the command result

Fine, will fix it tomorrow.

Any other issues?

2023-08-07 14:55 UTC, mpgn commented
Everything works perfectly for the rest :)

2023-08-08 07:26 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Waiting {}s for command completely executed.".format(self.interval_time))
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Save file to: " + resultTXT)
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Waiting {}s for command completely executed.".format(self.interval_time))
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Remove temporary files")
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Get result:")
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Adding base64 strings to registry, path: %s, keyname: %s"%(registry_Path,keyName))
Fixed

2023-08-08 07:27 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.highlight("[+] Remove temporary registry Key")
Fixed

2023-08-08 07:29 UTC, XiaoliChan commented
@mpgn Please review again

2023-08-08 13:18 UTC, mpgn approved these changes

2023-08-08 13:24 UTC, mpgn requested changes

2023-08-08 13:24 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +            self.logger.success(f"[+] Executed command: {self.command}")
the [+] should be removed 
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/30f63cfb-3630-4513-bdaf-6de57675392e)

2023-08-08 13:27 UTC, mpgn requested changes

2023-08-08 13:27 UTC, mpgn commented on cme/protocols/wmi/wmiexec_regout.py
> +            self.logger.highlight("Execute command failed, probabaly got detection by AV.")
self.logger.fail

2023-08-08 13:31 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +            self.logger.success(f"[+] Executed command: {self.command}")
Fixed

2023-08-08 15:04 UTC, mpgn approved these changes

2023-08-08 15:29 UTC, NeffIsBack commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Waiting {}s for command completely executed.".format(self.interval_time))
This is probably outputting `[+]` twice now

2023-08-08 15:30 UTC, NeffIsBack commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Save file to: " + resultTXT)
Same here and a few other in this file

2023-08-08 16:08 UTC, NeffIsBack commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Waiting {}s for command completely executed.".format(self.interval_time))
All good :) Thanks for the contribution

2023-08-08 16:09 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Waiting {}s for command completely executed.".format(self.interval_time))
Fixed

2023-08-08 16:09 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Save file to: " + resultTXT)
Fixed

2023-08-08 16:12 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_regout.py
> +        self.logger.info("[+] Waiting {}s for command completely executed.".format(self.interval_time))
> All good :) Thanks for the contribution

Thanks for you & @mpgn reviews. ❤

2023-08-09 08:55 UTC, mpgn approved these changes

2023-08-09 11:28 UTC, NeffIsBack commented
There are a lot of `%s` in the code. I think format strings is the new way to go, it would be nice if you could switch to it. I think there broke something because of `%s` once... just not worth it.

(If you don't know the syntax its `print(f"The user {user_name} is logged into system {system_name}.`)

2023-08-09 11:40 UTC, XiaoliChan commented
> 

I will fix it later

2023-08-10 06:46 UTC, XiaoliChan commented
@mpgn @NeffIsBack I rewrite the command execution module, now it is using WMI event to execute the command, no more `win32_process` (T1546.003)

2023-08-10 09:43 UTC, mpgn commented
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/8b225992-065a-41c2-8743-34366c7c9cfd)
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/8f6966bf-5bc3-476f-b180-48ad83c618d8)
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/af3b29bb-ba2e-4879-98c1-31ca68ba1019)

2023-08-10 09:45 UTC, XiaoliChan commented
@mpgn Awesome looks like it works prefect. I decide to add more info output in debug.

2023-08-10 09:47 UTC, mpgn commented
There is a problem with the output of the wmi command

![image](https://github.com/mpgn/CrackMapExec/assets/5891788/9c22be16-691d-4ad6-8f46-59d5f185e594)

2023-08-10 09:50 UTC, XiaoliChan commented
> There is a problem with the output of the wmi command
> 
> ![image](https://user-images.githubusercontent.com/5891788/259699091-9c22be16-691d-4ad6-8f46-59d5f185e594.png)

I know this problem, I try to split out that, but I got something weird, the result will be this
```
192.168.85.200 135 Host-A Result-AAAAAA-line1
192.168.85.201 135 Host-B Result-BBBBBBB-line1
192.168.85.200 135 Host-A Result-AAAAAA-line2
192.168.85.201 135 Host-B Result-BBBBBBB-line2
```

2023-08-10 09:51 UTC, mpgn commented
> I know this problem, I try to split out that, but I got something weird, the result will be this
192.168.85.200 135 Host-A Result-AAAAAA-line1
192.168.85.201 135 Host-B Result-BBBBBBB-line1
192.168.85.200 135 Host-A Result-AAAAAA-line2
192.168.85.201 135 Host-B Result-BBBBBBB-line2

It is exptected, it is because cme is threaded.
Otherwise you will not know which output is for which host

2023-08-10 09:56 UTC, XiaoliChan commented
> It is exptected, it is because cme is threaded. Otherwise you will not know which output is for which host
> 
> it is like this only if you run a comand over multiple hosts and the command result takes several lines

That why I did not split out the result

2023-08-10 10:01 UTC, mpgn commented
can you put the result of a command with the hostname etc info so I can test it ?

2023-08-10 10:07 UTC, XiaoliChan commented
@mpgn I make a commit

2023-08-10 10:19 UTC, mpgn commented
That is a problem on winrm I guess ^^

2023-08-10 10:22 UTC, mpgn commented
The file with the command result is never deleted on the victim's computer

![image](https://github.com/mpgn/CrackMapExec/assets/5891788/918f8f03-2844-4d8d-9935-4e15da3dd01c)

2023-08-10 10:25 UTC, XiaoliChan commented
> The file with the command result is never deleted on the victim's computer
> 
> ![image](https://user-images.githubusercontent.com/5891788/259709618-918f8f03-2844-4d8d-9935-4e15da3dd01c.png)

Well, the VBScript needs to improve.

2023-08-10 10:27 UTC, mpgn commented
Nop

2023-08-10 10:32 UTC, XiaoliChan commented
But if you want to clean up the temp file after the command executed, that may increase the time.

I think adding a '-clean' option is a good choice.

2023-08-10 11:25 UTC, mpgn commented
It should remove the file automaticaly, even if it's take more time

2023-08-10 11:44 UTC, NeffIsBack commented
What is the problem with removing the file?

2023-08-10 12:28 UTC, XiaoliChan commented
> What is the problem with removing the file?

Probably I'm thinking wrong.

2023-08-10 13:27 UTC, XiaoliChan commented
@mpgn Can you test this commit? it should do remove the file after the command executed [4c8cf57c4381b4a3c6229f00bf2d0669b6228883](https://github.com/XiaoliChan/CrackMapExec/commit/4c8cf57c4381b4a3c6229f00bf2d0669b6228883)

2023-08-10 20:33 UTC, mpgn commented
The file on the Temp folder is still present with the result of the command on my side

2023-08-11 00:06 UTC, NeffIsBack commented
> The file on the Temp folder is still present with the result of the command on my side

Did you checkout his commit?
> 4c8cf57c4381b4a3c6229f00bf2d0669b6228883

Not sure where this commit is located, but I see something like "filesystemobject delete file" in the commit changes

2023-08-11 01:00 UTC, XiaoliChan commented
weird, it the result file should be remove after that commit.

2023-08-11 01:12 UTC, XiaoliChan commented
@mpgn I just force push the commit, please test it again https://github.com/mpgn/CrackMapExec/commit/4c8cf57c4381b4a3c6229f00bf2d0669b6228883

2023-08-11 01:13 UTC, XiaoliChan commented
> Not sure where this commit is located, but I see something like "filesystemobject delete file" in the commit changes

Yes, now is doing file removal after command results load into wmi instance.

2023-08-11 02:52 UTC, XiaoliChan commented
I test that commit, and it works

Executed command
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/d1093f46-b15b-486e-950c-be3535df9ca5)

The temporary file was cleaned
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/95936248-544c-43c1-8a2c-5f6a8a153512)

2023-08-11 08:32 UTC, closed without merging