[New protocol] Add WMI support
mpgn/CrackMapExec pull request #81
Opened 2023-08-11 08:52 UTC by XiaoliChan

For more details: https://github.com/mpgn/CrackMapExec/pull/68

I just doing the wrong operation and the PR was broken 😟.

2023-08-11 08:56 UTC, XiaoliChan commented
@mpgn @NeffIsBack I rename the `wmiexec_classout` to `wmiexec_event`, and rewrite early version `wmiexec_regout` back and rename it to `wmiexec_normal`

![image](https://github.com/mpgn/CrackMapExec/assets/30458572/915d862d-dfcb-453c-98b1-5cfadfd60d05)

2023-08-11 09:48 UTC, mpgn requested changes

2023-08-11 09:48 UTC, mpgn commented on cme/protocols/wmi/wmiexec_normal.py
> +        command = fr'''$ProgressPreference="SilentlyContinue"; {self.shell} {command} 1> {result_output} 2>&1; [convert]::ToBase64String((Get-Content -path {result_output} -Encoding byte)) | set-cont
` cmd.exe /Q /c del /q /f /s C:\windows\temp\*`

it's a bit too much to delete all files, only the files used for the exec command should be deleted :)

2023-08-11 09:52 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_normal.py
> +        command = fr'''$ProgressPreference="SilentlyContinue"; {self.shell} {command} 1> {result_output} 2>&1; [convert]::ToBase64String((Get-Content -path {result_output} -Encoding byte)) | set-cont
HAHA 😂

2023-08-11 10:01 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_normal.py
> +        command = fr'''$ProgressPreference="SilentlyContinue"; {self.shell} {command} 1> {result_output} 2>&1; [convert]::ToBase64String((Get-Content -path {result_output} -Encoding byte)) | set-cont
Fixed

2023-08-12 03:08 UTC, XiaoliChan commented
`--no-output` is missing

2023-08-12 03:10 UTC, XiaoliChan commented
Another real-world attack example.

445 is blocked
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/0563fa45-f708-4ae9-84c7-b9909b295983)

135 is accept
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/c8ecdf77-8c7e-4cb2-b8de-c32b38d3c83a)

2023-08-12 12:01 UTC, XiaoliChan commented
@mpgn I change the default execute method to `wmiexec-normal`, looks like `wmiexec-event` is not stable when doing `iWbemServices.PutInstance`

As you can see, I'm not sure what broke, I believe something in impacket is wrong, but `wmiexec-normal` has no issues.
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/b806f635-8ac2-4709-ad1a-db3349a56e20)

2023-08-12 12:05 UTC, XiaoliChan commented
`--no-output` now is working

![image](https://github.com/mpgn/CrackMapExec/assets/30458572/2f82f05f-9c2c-4714-abc0-2b0d81ad421e)

2023-08-12 12:45 UTC, mpgn commented
Tell me when it's ready to review

2023-08-12 15:50 UTC, XiaoliChan commented
@mpgn Can do review now :)

2023-08-13 13:21 UTC, mpgn requested changes

2023-08-13 13:21 UTC, mpgn commented on cme/protocols/wmi/wmiexec.py
> +import time
already imported

2023-08-13 13:21 UTC, mpgn commented on cme/protocols/wmi/wmiexec.py
> +import uuid
already imported

2023-08-13 13:21 UTC, mpgn commented on cme/protocols/wmi/wmiexec.py
> +import base64
already imported

2023-08-13 13:22 UTC, mpgn commented
All good for the rest, file are correctly deleted

2023-08-13 16:00 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +import time
Removed

2023-08-13 16:00 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +import time
Removed

2023-08-13 16:01 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +import uuid
Removed

2023-08-13 16:01 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +import base64
Removed

2023-08-13 16:01 UTC, XiaoliChan commented
> All good for the rest, file are correctly deleted

Just doing force push :)

2023-08-13 16:22 UTC, NeffIsBack commented
> > All good for the rest, file are correctly deleted
> 
> Just doing force push :)

Ah yes. But if possible please avoid force-pushes. It's really hard to keep track what changed

2023-08-13 16:28 UTC, XiaoliChan commented
> Ah yes. But if possible please avoid force-pushes. It's really hard to keep track what changed

Ok, I will keep in mind.

2023-08-14 09:44 UTC, mpgn approved these changes

2023-08-14 12:25 UTC, NeffIsBack submitted a review, later dismissed
LGTM 👍

2023-08-15 17:47 UTC, XiaoliChan commented
When will this PR merge? I was really really excited for this.🤩

2023-08-16 11:00 UTC, XiaoliChan commented
@mpgn I just add the `firewall_checker` like the #97, just need to add in `admin_priv_check`, If it failed on firewall check, then the `admin_priv` is always false, which means can't use command execution modules.

2023-08-16 11:39 UTC, mpgn commented
Arrghhh why did you force push 🥲

2023-08-16 11:40 UTC, XiaoliChan commented
> Arrghhh why did you force push 🥲

Sorry, I just doing merge upstream to keep the fork up to date.

2023-08-16 11:42 UTC, XiaoliChan commented
> You can do `git merge master --no-commit`, i use it to update my branches from master

Keep in note!

2023-08-16 15:01 UTC, mpgn approved these changes

2023-08-16 17:25 UTC, NeffIsBack submitted a review, later dismissed
LGTM 👍

2023-08-19 03:10 UTC, XiaoliChan commented
@NeffIsBack Now I am doing the right merge HAHAHA.

2023-08-19 09:52 UTC, NeffIsBack commented
Close enough 😅

2023-08-23 03:46 UTC, XiaoliChan commented
Now it can invoke existed module

- enum_dns
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/d40f1588-a8d9-4904-bee2-d5feed61c78f)

- get_netconnections
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/003ba60e-7d38-4336-9fb2-588b72295c29)

And  `connection.execute("command", return_output)`

2023-08-23 04:36 UTC, XiaoliChan commented
The reason why doesn't need the firewall checker in "wmi query & execute" because it already checked in "check_if_admin" function

2023-08-23 09:16 UTC, mpgn commented
There is something wrong, the module enum-dns is set for SMB proto, you shouldn't be able to call it from wmi proto

https://github.com/mpgn/CrackMapExec/blob/master/cme/modules/enum_dns.py#L16C34-L16C34

2023-08-23 09:21 UTC, XiaoliChan commented
> There is something wrong, the module enum-dns is set for SMB proto, you shouldn't be able to call it from wmi proto
> 
> https://github.com/mpgn/CrackMapExec/blob/master/cme/modules/enum_dns.py#L16C34-L16C34

haha, I test it locally, just add “wmi” into support protocol

2023-08-23 09:22 UTC, mpgn commented
ahhh ok ! 👍

2023-08-23 09:23 UTC, mpgn commented
So this PR is dependant for PR #114 ?

2023-08-23 09:26 UTC, XiaoliChan commented
> So this PR is dependant of PR #114 ?

yes, I move the firewall checker into built in function

2023-08-23 12:09 UTC, XiaoliChan commented
@mpgn My fault, this PR current is not dependent on PR #114, if PR #114 is merged, then I can switch the `self.firewall_checker` into built-in `dcom_firewallchecker`.

Too many commit I did that I forgot somethings XD

2023-08-23 12:34 UTC, mpgn commented
We will merge the pr #114 before anyway ;)

2023-08-23 13:24 UTC, XiaoliChan commented
@mpgn @NeffIsBack Here is the todo list:

- Drop `wmi query` in `SMB` protocol
- Switch module `support_protocol` into `WMI` which is using `wmi query`
- Use #114 built-in functions `dcom_firewallchecker`

2023-08-23 16:13 UTC, mpgn commented
> Drop wmi query in SMB protocol

finaly we will keep it :)

2023-08-26 03:45 UTC, XiaoliChan commented
@mpgn @NeffIsBack The to-do list is done.

2023-08-26 13:25 UTC, XiaoliChan commented
One issue about CME I found, is when your target is a domain controller, like "ILOVECME.local", CME will make "ILOVECME.local" as `self.host`, because we know windows RPC string-binding also uses `target ip` or `target hostname` or `target FQDN` as binding strings, like

```
\\\\Hostname[\\PIPE\\atsvc]
\\\\IP[\\PIPE\\atsvc]
```

and you never see this
```
\\\\ILOVECME.local[\\PIPE\\atsvc]
```

That is why need to add that if condition.

2023-08-27 06:16 UTC, XiaoliChan commented
08/27/2023 update:
I figure out it, this is cause by `/etc/hosts` file (not CME issue)

```
192.168.85.200 xiaoli.local dc-2019 dc-2019.xiaoli.local
```

If `xiaoli.local` as first, then `AI_CANONNAME` with retrieve `xiaoli.local` as value, so changing the sequence of the domain is fine

```
192.168.85.200 dc-2019 xiaoli.local dc-2019.xiaoli.local
```

2023-08-30 00:13 UTC, XiaoliChan commented
@mpgn @NeffIsBack Confirm this PR can do review again now, after the `hostname` issue fixed.

2023-08-30 03:17 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +
Because we have did dcom check in `check_if_admin` function, so we don't need to try catch here

2023-08-30 03:17 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +
Same

2023-08-30 03:18 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +        self.__dcom.disconnect()
Same

2023-08-30 03:19 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec.py
> +            self.logger.debug(f"Target: {self.__host} removing temporary registry path error: {str(e)}")
Remove registry error is useless, turn it to debug

2023-08-30 03:45 UTC, XiaoliChan commented
@mpgn @NeffIsBack Confirm can do review again now.

2023-08-30 04:28 UTC, XiaoliChan commented on cme/modules/zerologon.py
> +                self.context.log.fail("Attack failed. Target is probably patched.")
Should tell the user if `zerologon` patched

2023-08-30 04:30 UTC, XiaoliChan commented on cme/modules/zerologon.py
> +    cme_logger.fail("This might have been caused by invalid arguments or network issues.")
`sys.stderr` useless in module

2023-08-30 04:31 UTC, XiaoliChan commented on cme/modules/zerologon.py
> +    cme_logger.fail("This might have been caused by invalid arguments or network issues.")
Also, should tell the users about `network issues` if check failure

2023-08-30 08:57 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +            if "dcom" in locals():
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/4f698b2c-1a8f-48ec-a506-71c5fb1f2ed6)

2023-08-30 10:01 UTC, mpgn commented on cme/modules/zerologon.py
> +                self.context.log.fail("Attack failed. Target is probably patched.")
Not a fail but a highlight

2023-08-30 10:01 UTC, XiaoliChan commented
After several rounds of real-world testing, no other bugs were found.

2023-08-30 10:30 UTC, XiaoliChan commented on cme/modules/zerologon.py
> +                self.context.log.fail("Attack failed. Target is probably patched.")
Done

2023-09-01 12:28 UTC, NeffIsBack requested changes

2023-09-01 12:28 UTC, NeffIsBack commented on cme/protocols/wmi/proto_args.py
> +                            "use in multiple hosts will may get crash. (try again if you get crash.)")
I would propose `"using on multiple hosts may crash (just try again if it crashed)."`

2023-09-01 12:28 UTC, NeffIsBack commented on cme/protocols/wmi/wmiexec_event.py
> +            vbs = fr'''
If it is not too much work i would actually prefer having this in a seperat file that would be loaded in from something like `protocols/wmi/wmiexec_event_script.vbs`. Variables could be just replaced after loading. An example what i mean would be like the `AddKeePassTrigger.ps1` or the `veeam_dump` powershell scripts are loaded.

I know i could have mentioned that earlier :D if it introduce even more problems just leave it as it is.

2023-09-01 12:32 UTC, XiaoliChan commented on cme/modules/enum_dns.py
> +    supported_protocols = ["wmi"]
HAHA, I am doing `move`, you are right, it should support smb also

2023-09-01 12:34 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_event.py
> +            vbs = fr'''
You are right, the vbs file shouldn't contain in the script, it's hard to read the code

2023-09-01 12:41 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +    def proto_flow(self):
Ha, I think this function can remove, because don't need to redefine `proto_flow` function here

2023-09-01 12:45 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +        except Exception as e:
Yes

2023-09-01 13:50 UTC, XiaoliChan commented on cme/modules/enum_dns.py
> +    supported_protocols = ["wmi"]
Done

2023-09-01 13:50 UTC, XiaoliChan commented on cme/modules/get_netconnections.py
> +    supported_protocols = ["wmi"]
Done

2023-09-01 13:50 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +    def proto_flow(self):
Fixed!

2023-09-01 13:51 UTC, XiaoliChan commented on cme/protocols/wmi.py
> +        except Exception as e:
Done

2023-09-01 13:51 UTC, XiaoliChan commented on cme/protocols/wmi/proto_args.py
> +                            "use in multiple hosts will may get crash. (try again if you get crash.)")
Fixed!

2023-09-01 13:51 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_event.py
> +            vbs = fr'''
Done

2023-09-01 13:54 UTC, NeffIsBack commented on cme/protocols/wmi/wmiexec_event.py
> +            vbs = fr'''
Ah perfect, this looks way cleaner

2023-09-01 13:55 UTC, NeffIsBack approved these changes
LGTM 👍

2023-09-01 13:56 UTC, XiaoliChan commented on cme/protocols/wmi/wmiexec_event.py
> +            vbs = fr'''
> Ah perfect, this looks way cleaner

Yes, good idea!

2023-09-01 13:58 UTC, NeffIsBack commented
If you encounter any issues or want to make improvements just open up a new PR based on this branch. That way we can soon merge the new protocol (This PR has already grown a lot :D )

2023-09-03 12:34 UTC, mpgn approved these changes

2023-09-03 15:32 UTC, XiaoliChan commented
@mpgn @NeffIsBack I know I'm not good at doing PR (made lots of ugly commits), but you are so patient to helping me review, I really appreciate it :D

2023-09-03 16:02 UTC, NeffIsBack commented
> @mpgn @NeffIsBack I know I'm not good at doing PR (made lots of ugly commits), but you are so patient to helping me review this PR, I'm really appreciate it :D

Glad to hear :) thank you for all your work and don't worry about messy commits, happens

2023-09-03 16:45 UTC, merged